<a href="https://colab.research.google.com/github/m-abdullah-nabeel/handwritten-digit-recognizer-sklearn/blob/main/Handwritten_Digit_Recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!pip install pillow mnist numpy sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [46]:
from PIL import Image
import numpy as np
import mnist
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [47]:
x_train = mnist.train_images()
y_train = mnist.train_labels()

In [48]:
x_test = mnist.test_images()
y_test = mnist.test_labels()

In [49]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [50]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [51]:
x_train.shape

(60000, 28, 28)

In [52]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [53]:
y_train.shape

(60000,)

In [54]:
x_train = x_train.reshape(-1, 28*28)

In [55]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [56]:
x_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [57]:
x_test.shape

(10000, 28, 28)

In [58]:
x_test = x_test.reshape(-1, 28*28)

In [59]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [60]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [61]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [62]:
x_train[0].shape

(784,)

In [63]:
# x_train = (x_train/256)
# y_train = (y_train/256)

In [64]:
# x_train[0]

In [65]:
mlp = MLPClassifier(hidden_layer_sizes=(64,64), solver="adam", activation='relu', verbose=10)

# mlp = MLPClassifier(
#     hidden_layer_sizes=(64,64),
#     max_iter=8,
#     alpha=1e-4,
#     solver="sgd",
#     verbose=10,
#     random_state=1,
#     learning_rate_init=0.2,
# )

In [66]:
mlp.fit(x_train, y_train)

Iteration 1, loss = 2.65005867
Iteration 2, loss = 0.61199416
Iteration 3, loss = 0.37591645
Iteration 4, loss = 0.28020115
Iteration 5, loss = 0.22703745
Iteration 6, loss = 0.18937338
Iteration 7, loss = 0.17153639
Iteration 8, loss = 0.15249567
Iteration 9, loss = 0.14038969
Iteration 10, loss = 0.13089823
Iteration 11, loss = 0.12406477
Iteration 12, loss = 0.11752591
Iteration 13, loss = 0.10451802
Iteration 14, loss = 0.11022529
Iteration 15, loss = 0.10589689
Iteration 16, loss = 0.09554521
Iteration 17, loss = 0.08981600
Iteration 18, loss = 0.08962475
Iteration 19, loss = 0.08668399
Iteration 20, loss = 0.07954313
Iteration 21, loss = 0.08365879
Iteration 22, loss = 0.07906706
Iteration 23, loss = 0.06969020
Iteration 24, loss = 0.06354883
Iteration 25, loss = 0.06707900
Iteration 26, loss = 0.06975190
Iteration 27, loss = 0.06419355
Iteration 28, loss = 0.05796677
Iteration 29, loss = 0.05234218
Iteration 30, loss = 0.05182576
Iteration 31, loss = 0.04855188
Iteration 32, los

MLPClassifier(hidden_layer_sizes=(64, 64), verbose=10)

In [69]:
predictions = mlp.predict(x_test)

In [70]:
acc = confusion_matrix(y_test, predictions)

In [71]:
acc

array([[ 962,    0,    0,    1,    0,    1,    4,    5,    7,    0],
       [   0, 1121,    0,    3,    2,    3,    1,    1,    3,    1],
       [   3,    2,  963,   22,    3,    1,    5,   12,   21,    0],
       [   0,    1,    4,  979,    0,   12,    0,    2,    8,    4],
       [   0,    1,    0,    0,  959,    0,    5,    2,    1,   14],
       [   3,    1,    0,   11,    2,  856,   12,    0,    4,    3],
       [   6,    2,    0,    0,    4,    2,  937,    0,    7,    0],
       [   0,    6,   11,    4,    1,    1,    0,  983,    7,   15],
       [   4,    1,    2,   11,    6,    7,    4,    5,  931,    3],
       [   0,    3,    1,    6,   15,    8,    1,    5,    4,  966]])

In [72]:
def accuracy(cm):
  diagonal = cm.trace()
  elem = cm.sum()
  return diagonal/elem

In [73]:
accuracy(acc)

0.9657

In [78]:
mlp.predict([x_test[90]])

array([3], dtype=uint8)